#!/usr/bin/env python
#_*_ coding: utf8 _*_

### === ESCALATION OF PRIVILEGES LINUX CVE SUDO === ###
import argparse
import os
from datetime import datetime,date

W = '\033[0;37m'
R = '\033[1;31m'  # red
G = '\033[1;32m'  # green
O = '\033[1;33m'  # orange
B = '\033[1;34m'  # blue
P = '\033[1;35m'  # purple
C = '\033[1;36m'  # cyan

date = datetime.now()

parse = argparse.ArgumentParser()
parse.add_argument("-m", "--module", help="Active Modules ")
parse.add_argument("-b","--search", help="Search modules")
parse.add_argument("-l","--list", help="Show list of modules")
parse.add_argument("-u","--user", help="Set user without privileges")
parse = parse.parse_args()

OK = W+"[ "+G+"OK "+W+"] Module "+str(parse.module)+" used"

if parse.list:
	os.system("cat .data")
if parse.search:
	os.system("cat .head")
	os.system("cat .data | grep '"+parse.search+"'")
	os.system("cat .end")
if parse.module:
	if parse.module == "simple":
		print(B+"[*]"+W+"testing first level segurity...")
		print(B+"[*]"+W+"Enter password of the user "+parse.user)
		os.system("sudo -sH")
		print(OK)
		print(G+"[INFO]"+W+" Time:"+C+str(date))
	if parse.module == "search":
		print(G+"[+] "+W+"Searching...")
		os.system("sudo -l")
		d = raw_input(R+"do you want to continue?(y/n)")
		if d == "y" or d == "Y":
			print(G+"[+] "+W+"Researching...")
			os.system("find / -perm -u=s -type f 2>/dev/null")
		else:
			print(OK)
	if parse.module == "files":
		print(B+"[X] "+W+"Results: ")
		os.system("ls -la /*/* | grep '"+parse.user+"'")
		
